Backport PR #1017: Add `require` to list of modules to try fixing kernel.js loading.
This would likely fix some failures ithat happend with `kernel.js` with
the following on the js console:

> Uncaught (in promise) TypeError: require is not a function

...